language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer install

script:
  - vendor/bin/phpunit

jobs:
  include:
    - stage: docker test
      php: 7.3
      before_script: ignore
      script:
      - make composer-install
      - make test

notifications:
  email: false

services:
  - docker

branches:
  only:
    - master